name: demo1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  icons_plus: ^5.0.0
  avatar_glow: ^3.0.1
  flutter_tts: ^4.0.2
  speech_to_text: ^7.0.0
  url_launcher: ^6.1.10
  url_launcher_android: ^6.1.10
  device_preview: ^1.2.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  image: ^4.2.0
  flutter_spinkit: ^5.2.1
  audioplayers: ^6.4.0
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  provider: ^6.1.4
  flutter_markdown: ^0.7.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  google_generative_ai: ^0.4.7
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  animated_text_kit: ^4.2.1
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^7.1.2
  flutter_slidable: ^4.0.0
  animate_do: ^4.2.0
  flutter_animate: ^4.5.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/bg1.jpg
    - assets/images/michael_scott.jpg
    - assets/images/michael_scott.jpg
    - assets/images/
    - .env
 